dist: trusty
sudo: true
language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0

jdk:
  - oraclejdk8

# Branches to test
branches:
  only:
    - master

notifications:
  email:
    recipients:
      - ross@mongodb.com
    on_success: change
    on_failure: always

matrix:
    fast_finish: true

env:
  matrix:
    - MONGODB=4.0.5


install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
  - echo $TRAVIS_SCALA_VERSION

script:
  - ./sbt ++$TRAVIS_SCALA_VERSION check

after_script:
  - pkill mongod
